Csalas navbar
dev-mission/ecofoodie pull request #9
Opened 2020-03-24 03:16 UTC by SalasC2

2020-03-24 04:20 UTC, francisli requested changes
This doesn't seem to match the designs in Figma- when you open the EcoFoodie project in Figma, make sure to switch to "Version 2" in the pages list to see the latest version.

It should have a light green background, and links on the header that collapse into a menu on mobile...?

<img width="442" alt="Screen Shot 2020-03-23 at 9 19 29 PM" src="https://user-images.githubusercontent.com/140766/77387963-1249f400-6d4c-11ea-80bb-cd716c8c389e.png">
<img width="776" alt="Screen Shot 2020-03-23 at 9 18 08 PM" src="https://user-images.githubusercontent.com/140766/77387967-137b2100-6d4c-11ea-915a-2d0a082be172.png">

2020-03-25 01:10 UTC, SalasC2 commented
Changed navbar to match 
![Expected Navbar](https://user-images.githubusercontent.com/8258919/77491268-86db6c00-6dfa-11ea-9341-7e3e6e082743.jpg)

On actual website
![Website Navbar](https://user-images.githubusercontent.com/8258919/77491217-67444380-6dfa-11ea-87ef-f0afa6879971.jpg)

TODO: Still need to add logic to change between sign in and sign out depending on whether a user is logged in or not.

2020-03-25 01:15 UTC, francisli commented on views/layout.ejs
> +    <link href="stylesheets/bootstrap.css" rel="stylesheet">
Did it not work to simply override certain styles in Bootstrap?

By copying the entire file and then modifying specific styles, that makes it more difficult to upgrade the Bootstrap version...?

2020-03-25 01:17 UTC, francisli commented
Also need to override button and nav link styles to match the green...?

2020-03-25 01:18 UTC, francisli commented
Does this collapse properly on narrow widths (I.e. phone?)

2020-03-26 00:40 UTC, merged

2020-03-26 00:40 UTC, francisli commented
Ok, I'm going to merge this in and delete the branch, so pull the latest on master and create a new branch for continued work...